import { Router } from 'express';
import { resend } from '../lib/resend';

const router = Router();

router.post('/send-invoice', async (req, res) => {
  try {
    const {
      email,
      companyName,
      employeeName,
      amount,
      period,
      invoiceUrl,
      employeeWallet,
    } = req.body;

    if (!email || !companyName || !employeeName || !amount || !period || !invoiceUrl) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const result = await resend.emails.send({
      from: process.env.EMAIL_FROM!,
      to: email,
      subject: 'Your PayFlow salary invoice is ready',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>Your salary payment has been processed</h2>
          <p><strong>Company:</strong> ${companyName}</p>
          <p><strong>Employee:</strong> ${employeeName}</p>
          <p><strong>Amount:</strong> ${amount} USDC</p>
          <p><strong>Period:</strong> ${period}</p>
          <p><strong>Wallet:</strong> ${employeeWallet ?? '-'}</p>
          <p>
            <a href="${invoiceUrl}" style="display:inline-block;padding:12px 18px;background:#2563eb;color:white;text-decoration:none;border-radius:8px;">
              View Invoice
            </a>
          </p>
          <p>This invoice was generated by PayFlow on Injective.</p>
        </div>
      `,
    });

    res.json({ success: true, result });
  } catch (error: any) {
    res.status(500).json({ error: error.message || 'Failed to send invoice email' });
  }
});

export default router;